# Generated by Django 4.2.5 on 2023-09-22 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_diretorio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='diretorio',
            field=models.ImageField(default='/rides/static/img', upload_to=None),
        ),
    ]
